MSS:
    host: 'https://10.50.44.141'
    headers:
        Content-Type: 'application/json'
        Authorization: 'token'

    # 登陆接口
    mss_login:
      method: post
      headers:
        Content-Type: 'application/json'
        Authorization: 'token'
      api: '/assetApi/api/authenticate'

    # 资产列表查询
    asset_list_query:
      method: post
      headers:
        Content-Type: 'application/json'
        Authorization: ''
      web_api: '/assetApi/api/asset/web/list'
      domain_api: '/assetApi/api/asset/domain/list'
      ip_api: '/assetApi/api/asset/ip/list'
      port_api: '/assetApi/api/asset/port/pcList'

    # 系统管理-新增单位
    system_add_unit:
      method: post
      headers:
        Content-Type: 'application/json'
        Authorization: ''
      api: '/assetApi/api/sys/org/create'

    # 系统管理-新增用户
    system_create_user:
      method: post
      headers:
        Content-Type: 'application/json'
        Authorization: ''
      api: '/assetApi/api/sys/user/createUser'
